<h2>Formulaire de demande au service client</h2>
<form action="" method="POST">
        <div class="mb-3">
            <label for="lastname">Prénom*</label>
            <input class="form-control" type="text" name="lastname" id="lastname" placeholder="Votre prénom" maxlength=255 required>
        </div>
        <div class="mb-3">
            <label for="firstname">Nom*</label>
            <input class="form-control" type="text" name="firstname" id="firstname" placeholder="Votre nom" maxlength=255 required>
        </div>
        <div class="mb-3">
            <label for="email">E-mail*</label>
            <input class="form-control" type="email" name="email" id="email" placeholder="Votre e-mail" maxlength=255 required>
        </div>
        <div class="mb-3">
            <label for="phone">N° de téléphone</label>
            <input class="form-control" type="tel" name="phone" id="phone" placeholder="Votre n° de téléphone" maxlength=40>
        </div>
        <div class="mb-3">
            <label for="demand subject">Sujet de la demande*</label>
            <select name="subjet" id="select" required>
                <option value="" selected="false">--Veuillez sélectionner un sujet--</option>
                <option value="Mon profil / administratif">Mon profil / administratif</option>
                <option value="Ma carte bancaire">Ma carte bancaire</option>
                <option value="Mes services">Mes services</option>
                <option value="Offres commerciales">Offres commerciales</option>
                <option value="Sécurité et fraudes">Sécurité et fraudes</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="Message">Message*</label>
            <textarea class="form-control" type="textarea" name="message" id="message" minlength=100 required></textarea>
        </div>

        <p>Joindre un fichier <input type="file" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/rtf,application/vnd.oasis.opendocument.text"></p>

        <button class="btn btn-primary">VALIDER</button>
</form>
