<!-- Ajouter un statut -->
<h2>Ajouter un statut de traitement de requête</h2>
<form action="" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="status">Nouveau statut</label>
            <input class="form-control" type="text" name="status" id="status" placeholder="Nouveau statut" maxlength=255 required/>
        </div>
        <div class="mb-3">
            <label for="label">Label</label>
            <input class="form-control" type="text" name="label" id="label" placeholder="Nouveau label" maxlength=255 required/>
        </div>
        
        
    
        

        <input value="Valider" type="submit" name="submit" class="btn btn-dark"/>
</form>

<div class="">
    <?= $flashMessage; ?>
</div>
