<!-- Liste des statuts -->
<div class="text-center pt-3 pb-2">
    <img src="img/logo.png" alt="Logo" width="60">
    <h2 class="my-4">Liste des statuts</h2>

    <table class="table table-striped bg-white">
  <thead>
    <tr>
      <th scope="col">#id</th>
      <th scope="col">Label</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php 
    foreach ($statusData as $data) {
    ?>
        <tr class="text-break">
        <th scope="row"><?= $data["id_status"] ?></th>
        <td><?= $data["status_label"] ?></td>
        <td>
          <a href="/status/edit?id_status=<?= $data['id_status'] ?>"><button><i class="far fa-edit"></i></button></a>
          <a href="/status/delete?id_status=<?= $data['id_status'] ?>"><button><i class="fas fa-trash-alt"></i></button></a>
        </td>

        </tr>
    <?php
    }
    ?>
  </tbody>
</table>
</div>



<!-- Affichage du message flash le cas échéant -->
<?php if ($flashMessage): ?>
    <div class="alert alert-success text-center pt-3 pb-4"><?=htmlspecialchars($flashMessage);?></div>
<?php endif; ?>
