<!-- Formulaire demande client -->
<h2>Ajouter une demande client</h2>
<form action="" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="lastname">Nom*</label>
            <input class="form-control" type="text" name="lastname" id="lastname" placeholder="Votre nom" maxlength=255 required/>
        </div>

        <div class="mb-3">
            <label for="firstname">Prénom*</label>
            <input class="form-control" type="text" name="firstname" id="firstname" placeholder="Votre prénom" maxlength=255 required/>
        </div>

        <div class="mb-3">
            <label for="email">E-mail*</label>
            <input class="form-control" type="email" name="email" id="email" placeholder="Votre e-mail" maxlength=255 required/>
        </div>

        <div class="mb-3">
            <label for="phone">N° de téléphone</label>
            <input class="form-control" type="tel" name="phone" id="phone" placeholder="Votre n° de téléphone" maxlength=40/>
        </div>

        <div class="mb-3">
            <label for="demand subject">Sujet de la demande*</label>
            <select name="subject_id" id="select" required>
                <option value="" selected="false">--Veuillez sélectionner un sujet--</option>
                <option value="1">Mon profil / administratif</option>
                <option value="2">Ma carte bancaire</option>
                <option value="3">Mes services</option>
                <option value="4">Offres commerciales</option>
                <option value="5">Sécurité et fraudes</option>
            </select>
        </div> 

        <div class="mb-3">
            <label for="Message">Message*</label>
            <textarea class="form-control" type="textarea" name="content" id="message" minlength=100 maxlength=1000 required></textarea>
        </div>

        <p>Joindre un fichier <input type="file" name="document" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/rtf,application/vnd.oasis.opendocument.text"/></p>

        <input value="Valider" type="submit" name="submit" class="btn btn-dark"/>
</form>

<div class="">
    <?= $flashMessage; ?>
</div>
