<!-- Edition demande client -->
<h2>Requête du <?= $request->getCreatedAt() ?> de <?= $request->getFullname() ?></h2>

<p>Email : <?= $request->getEmail() ?></p>
<p>Téléphone : <?= $request->getPhone() ?></p>
<p>Sujet : <?= $request->getSubject()->getSubjectLabel() ?></p>
<p>Message</p>
<p><?= $request->getContent() ?></p>
<p>Fichier joint : <?= $request->getFilename() ?></p>

<p>Statut</p>
<label for="demand subject"></label>
    <select name="subject_id" id="select">



        <input value="Valider" type="submit" name="submit" class="btn btn-dark"/>


<div class="">
    <?= $flashMessage; ?>
</div>
