<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blue Bank</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

<body>
<section class="vh-100 gradient-custom-2">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-xl-10">
                    <div class="mask-custom">
                        <div class="card-body p-4 text-black">

                            <header>
                                <?php include '../templates/layout/header.phtml';?>
                            </header>
                            <main class="container">                                
                                <?php include '../templates/pages/' . $template . '.phtml';?>
                            </main>
                            <footer>
                                <?php include '../templates/layout/footer.phtml';?>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

</html>
 