

    <nav>
        <a href="/" class="btn btn-dark mx-1">
            <i class="fa-solid fa-home"></i>
            Accueil
        </a>

        <a href="/requests/add" class="btn btn-dark mx-1">
            <i class="fa fa-file-text" aria-hidden="true"></i>
            Formulaire demande client
        </a>  

        <a href="/requests/" class="btn btn-dark mx-1">
            <i class="fa fa-file-text" aria-hidden="true"></i>
            Demandes clients
        </a>    

        <a href="/subjects/" class="btn btn-dark mx-1">
            <i class="fa fa-file-text" aria-hidden="true"></i>
            Listes des sujets de requête
        </a>            
        
        <a href="/status/" class="btn btn-dark mx-1">
            <i class="fa fa-file-text" aria-hidden="true"></i>
            Listes des statuts
        </a>     
    </nav>